# Generated by Django 5.0.3 on 2024-03-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=225),
        ),
    ]
